name: Automated Actix Tests

on:
  pull_request:
    branches: [ master ]
  workflow_dispatch:
     branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing:
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
    - name: Fetch Config
      run: echo "${{ secrets.APP_CONFIG }}" > .env
    - name: Node Mail Test
      run: |
        cd scripts/mailer
        npm install --no-save
        node index.js
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test -- --show-output
